services:
  backup:
    image: jaroslawdutka/bitjuice-backup:latest
    container_name: bitjuice-backup
    restart: unless-stopped
    environment:
      - BACKUP_CRON_SCHEDULE=0 2 * * *
      - BACKUP_WORKFLOW_FILE=config/workflow.yml
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
