'@module': streaming-workflow
description: Backup home directories to cloud
providers:
  - '@module': directory-provider
    paths:
      - /home/user
    rewrites:
      - from: /home
        to: /users
aggregator:
  '@module': tgz-aggregator
  filename: backup.tar.gz
storage:
  '@module': file-storage
  path: /backup
  